# Generated by Django 5.2.5 on 2025-09-25 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['-departure_time']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['row', 'seat']},
        ),
        migrations.RenameField(
            model_name='airplane',
            old_name='seats_in_rows',
            new_name='seats_in_row',
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('flight', 'row', 'seat')},
        ),
    ]
