# Generated by Django 5.2.5 on 2025-09-29 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_api', '0002_alter_flight_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='airplanetype',
            options={'verbose_name': 'airplane type', 'verbose_name_plural': 'airplane types'},
        ),
        migrations.AlterModelOptions(
            name='flight',
            options={},
        ),
        migrations.AlterField(
            model_name='airport',
            name='closest_big_city',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='airport_api.country')),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'unique_together': {('name', 'country')},
            },
        ),
    ]
