# Generated by Django 5.2.5 on 2025-09-29 14:09

import airport_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_api', '0003_country_alter_airplanetype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplanetype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=airport_api.models.upload_image_path),
        ),
    ]
