# Generated by Django 5.2.5 on 2025-09-29 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_api', '0004_airplanetype_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='closest_big_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airports', to='airport_api.city'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
